version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    image: student-wiki-api
    build: ./backend/server
    environment:
      - MONGO=mongo
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
  frontend:
    image: student-wiki
    build: ./frontend
    ports:
      - "80:80"